<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="$(arg robot_name)">

    <!-- Define input arguments -->
    <xacro:arg name="simulate" default="true" />

    <!-- Define parameters -->
    <xacro:property name="name" value="$(arg robot_name)" />

    <!-- Include other xacro files here -->
    <xacro:include filename="inertial_calculations.xacro" />
    <xacro:include filename="${name}_materials.xacro" />
    <xacro:include filename="${name}_params.xacro" />


    <!-- Load ros2 and gazebo plugins -->
    <xacro:include filename="${name}.ros2_control.xacro" />
    <xacro:robot_ros2_control />
    <xacro:if value="$(arg simulate)">
        <xacro:include filename="${name}_gazebo.xacro" />
        <xacro:diffbot_gazebo />
    </xacro:if>

    <!-- Base link -->
    <link name="base_link" />

    <!-- Position of the chassis link with respect to the base link -->
    <joint name="chassis_joint" type="fixed">
        <origin xyz="0.01 0 0" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="chassis_link" />
    </joint>

    <!-- Chassis -->
    <link name="chassis_link">
        <visual>
            <origin xyz="${base_width/2 - wheel_x_from_back} 0 ${base_height/2-wheel_z_from_base}"
                rpy="0 0 0" />
            <geometry>
                <box size="${base_width} ${base_depth} ${base_height}" />
            </geometry>
            <material name="red" />
        </visual>
        <collision>
            <origin xyz="${base_width/2 - wheel_x_from_back} 0 ${base_height/2-wheel_z_from_base}"
                rpy="0 0 0" />
            <geometry>
                <box size="${base_width} ${base_depth} ${base_height}" />
            </geometry>
        </collision>
        <xacro:inertial_box mass="${base_mass}" x="${base_width}" y="${base_depth}"
            z="${base_height}">
            <origin xyz="${base_width/2 - wheel_x_from_back} 0 ${base_height/2-wheel_z_from_base}"
                rpy="0 0 0" />
        </xacro:inertial_box>
    </link>

    <joint name="wheel_l_joint" type="continuous">
        <origin xyz="0 ${base_depth/2+wheel_height+0.005} 0" rpy="${pi/2} 0 0" />
        <parent link="base_link" />
        <child link="wheel_l_link" />
        <axis xyz="0 0 -1" />
    </joint>

    <link name="wheel_l_link">
        <visual>
            <origin xyz="0 0 ${wheel_height/2}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${wheel_r}" length="${wheel_height}" />
            </geometry>
            <material name="black" />
        </visual>
        <collision>
            <origin xyz="0 0 ${wheel_height/2}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${wheel_r}" length="${wheel_height}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" r="${wheel_r}" h="${wheel_height}">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_cylinder>
    </link>

    <joint name="wheel_r_joint" type="continuous">
        <origin xyz="0 -${base_depth/2+0.005} 0" rpy="${pi/2} 0 0" />
        <parent link="base_link" />
        <child link="wheel_r_link" />
        <axis xyz="0 0 -1" />
    </joint>

    <link name="wheel_r_link">
        <visual>
            <origin xyz="0 0 ${wheel_height/2}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${wheel_r}" length="${wheel_height}" />
            </geometry>
            <material name="black" />
        </visual>
        <collision>
            <origin xyz="0 0 ${wheel_height/2}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${wheel_r}" length="${wheel_height}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" r="${wheel_r}" h="${wheel_height}">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_cylinder>
    </link>

    <joint name="caster_joint" type="fixed">
        <origin xyz="${base_width - wheel_x_from_back - caster_r} 0 ${-wheel_r + caster_r}"
            rpy="0 0 0" />
        <parent link="chassis_link" />
        <child link="caster_link" />
    </joint>

    <link name="caster_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <sphere radius="${caster_r}" />
            </geometry>
            <material name="gray" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <sphere radius="${caster_r}" />
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_mass}" r="${wheel_r}">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_sphere>
    </link>
</robot>